import type { Metadata } from "next";
import { PageShell, Section } from "@/components/page-shell";

const LAST_UPDATED = "3 August 2026";

export const metadata: Metadata = {
  title: "Terms of use",
  description:
    "The terms this preview of Argus is offered under: what it is, what it isn't, and what you agree to when you use it.",
};

export default function TermsPage() {
  return (
    <PageShell
      eyebrow={`Terms · updated ${LAST_UPDATED}`}
      title="Terms of use"
      lede="Short and readable, because a preview of a capstone project does not need ten pages of boilerplate."
    >
      <Section title="What Argus is">
        <p>
          Argus is a research preview that generates AI-written meeting briefs
          from public sources. It is offered free of charge, as-is, with no
          service-level commitment. Features and availability may change or stop
          without notice.
        </p>
      </Section>

      <Section title="Verify before you act">
        <p>
          Briefs are generated by a language model from evidence gathered
          automatically. They can be incomplete, out of date, or wrong. Every claim
          carries a citation precisely so you can check it — the responsibility for
          anything you say or decide off the back of a brief is yours.
        </p>
        <p>
          Argus is not legal, financial, investment or employment advice, and must
          not be used as the basis for a decision about a person&apos;s employment,
          credit or similar.
        </p>
      </Section>

      <Section title="Acceptable use">
        <ul className="list-disc space-y-2 pl-5">
          <li>Use Argus for legitimate business research and meeting preparation.</li>
          <li>
            Do not use it to harass, stalk, profile or build dossiers on private
            individuals.
          </li>
          <li>
            Do not attempt to overload the service, bypass its limits, or use it in
            ways that breach the terms of the underlying data sources.
          </li>
          <li>
            Respect the copyright of cited sources when you reuse anything a brief
            surfaces.
          </li>
        </ul>
      </Section>

      <Section title="Content and ownership">
        <p>
          You keep whatever you type. Generated briefs are yours to use in your own
          work. Cited material remains the property of its original publisher — a
          citation is a pointer, not a licence.
        </p>
        <p>
          The Argus source code is released under the MIT licence; the name and
          mark are not. Details are on the{" "}
          <a href="/about#open-source" className="text-accent underline-offset-4 hover:underline">
            about page
          </a>
          .
        </p>
      </Section>

      <Section title="No warranty, no liability">
        <p>
          To the fullest extent permitted by law, Argus is provided without
          warranties of any kind, and the team behind it is not liable for any loss
          arising from its use or unavailability.
        </p>
      </Section>

      <Section title="Getting in touch">
        <p>
          Questions about these terms go to the{" "}
          <a href="/contact" className="text-accent underline-offset-4 hover:underline">
            contact page
          </a>
          . If we change them materially, the date at the top of this page changes
          with them.
        </p>
      </Section>
    </PageShell>
  );
}
